"""Cone membership: is an inequality implied by the generators?

With an extra coordinate for the constant term, the condition says that
the target t = (v, v0) lies in the convex cone generated by the columns
g_j = (a_j, b_j) and the slack column (0, 1). By Farkas' lemma exactly one
of the following holds:

    TRUE:   t = sum y_j g_j  with  y >= 0           (a proof)
    FALSE:  z.g_j <= 0 for all j,  and  z.t > 0      (a counterexample)

Both certificates are computed in floating point by non-negative least
squares: the projection of t onto the cone gives y, its residual z. They
are then verified in exact rational arithmetic. Only if the verification
fails, the exact simplex method decides (which is much slower for many
variables, as these LPs are highly degenerate).
"""
from __future__ import annotations

from fractions import Fraction
from math import gcd, isqrt
from functools import reduce

from .generators import Generator, count_elemental
from .linalg import exact_solve, nnls, simplex

SparseCol = list[tuple[int, Fraction]]

# Number of times the exact simplex method had to decide (for testing).
SIMPLEX_FALLBACKS = [0]


def homogenize(gens: list[Generator], nvars: int, v: dict[int, Fraction]):
    """Homogenized columns and target.

    Coordinates: subset bitmask S -> S (for S = 1..D-1), constant term -> D
    (using 1-based D like the Julia original; here D = 2**nvars, and we
    store it as the dict key D meaning "the constant coordinate").
    """
    D = 1 << nvars
    cols: list[SparseCol] = []
    for g in gens:
        c = list(g.a)
        if g.b != 0:
            c.append((D, g.b))
        cols.append(c)
    cols.append([(D, Fraction(1))])    # slack: 1 >= 0
    t: SparseCol = [((D if k == 0 else k), x) for k, x in v.items() if x != 0]
    return D, cols, t


def sdot(c: SparseCol, z: list) -> Fraction:
    total = 0
    for k, x in c:
        total += x * z[k]
    return total


def todense(c: SparseCol, D: int, as_float: bool = False):
    x = [0.0 if as_float else Fraction(0)] * (D + 1)
    for k, v in c:
        x[k] += (float(v) if as_float else v)
    return x


def certify_true(cols: list[SparseCol], t: SparseCol, support: list[bool]):
    """TRUE certificate: exact non-negative y with sum_{j in support} y_j g_j = t,
    as a vector over all columns. None if the support does not yield one.
    """
    S = [j for j, keep in enumerate(support) if keep]
    rows = sorted({k for j in S for k, _ in cols[j]} | {k for k, _ in t})
    index = {k: i for i, k in enumerate(rows)}
    M = [[Fraction(0)] * len(S) for _ in rows]
    for c, j in enumerate(S):
        for k, x in cols[j]:
            M[index[k]][c] += x
    rhs = [Fraction(0)] * len(rows)
    for k, x in t:
        rhs[index[k]] += x
    y = exact_solve(M, rhs)
    if y is None or any(v < 0 for v in y):
        return None
    full = [Fraction(0)] * len(cols)
    for c, j in enumerate(S):
        full[j] = y[c]
    return full


def certify_false(cols: list[SparseCol], lines: list[int], t: SparseCol,
                   r: list[float], nvars: int, D: int):
    """FALSE certificate: exact z with z.g_j <= 0 for all columns and
    z.t > 0, obtained from the floating point residual r.
    """
    def f(k: int) -> int:
        return k * (2 * nvars + 1 - k)

    # Index 0 is an unused dummy so that w lines up with the (D+1)-length
    # dense vectors used throughout (index k in 1..D-1 for subset k, D for
    # the constant term).
    w = [0] + [-f(bin(S).count("1")) for S in range(1, D)] + [-1]
    peak = max(abs(x) for x in r) if r else 1.0
    scale = (2.0 ** 50) / peak if peak else 1.0
    zr = [round(x * scale) for x in r]
    nel = count_elemental(nvars)
    lines_set = set(lines)
    rnorm = sum(x * x for x in r) ** 0.5
    tight = []
    for j in range(nel, len(cols)):
        if j in lines_set:
            continue
        val = sum(x * r[k] for k, x in cols[j])
        if val >= -1e-9 * rnorm:
            tight.append(j)
    proj = list(lines) + tight
    E = [[Fraction(0)] * len(proj) for _ in range(D + 1)] if proj else None
    if E is not None:
        for c, j in enumerate(proj):
            for k, v in cols[j]:
                E[k][c] += v

    shift = 0
    limit = 1 << 30
    while shift <= limit:
        z = [Fraction(zv) + shift * wv for zv, wv in zip(zr, w)]
        if E is not None:
            # z -= E lam  with  E^T E lam = E^T z  (any solution gives the projection)
            EtE = [[sum(E[k][p] * E[k][q] for k in range(D + 1)) for q in range(len(proj))]
                   for p in range(len(proj))]
            Etz = [sum(E[k][p] * z[k] for k in range(D + 1)) for p in range(len(proj))]
            lam = exact_solve(EtE, Etz)
            for k in range(D + 1):
                acc = Fraction(0)
                for p in range(len(proj)):
                    acc += E[k][p] * lam[p]
                z[k] -= acc
        if sdot(t, z) <= 0:
            return None
        if all(sdot(c, z) <= 0 for c in cols):
            return z
        shift = 1 if shift == 0 else 2 * shift
    return None


def certify_false_exact(cols: list[SparseCol], t: SparseCol, passive: list[bool], D: int):
    """FALSE certificate, computed exactly: the residual of the projection
    of t onto the span of the passive columns of the least squares solution.
    """
    idx = [j for j, keep in enumerate(passive) if keep]
    AP = [[Fraction(0)] * len(idx) for _ in range(D + 1)]
    for c, j in enumerate(idx):
        for k, v in cols[j]:
            AP[k][c] += v
    tt = [Fraction(0)] * (D + 1)
    for k, v in t:
        tt[k] += v
    k = len(idx)
    AtA = [[sum(AP[row][p] * AP[row][q] for row in range(D + 1)) for q in range(k)]
           for p in range(k)]
    Atb = [sum(AP[row][p] * tt[row] for row in range(D + 1)) for p in range(k)]
    y = exact_solve(AtA, Atb)
    z = tt[:]
    if y is not None:
        for c, j in enumerate(idx):
            for row in range(D + 1):
                z[row] -= AP[row][c] * y[c]
    if sdot(t, z) > 0 and all(sdot(c, z) <= 0 for c in cols):
        return z
    return None


def decide(gens: list[Generator], nvars: int, v: dict[int, Fraction],
           method: str = "auto"):
    """Is  v.h + v[0] >= 0  implied by the generators?

    Returns ``(verdict, certificate)``. The certificate is a list ``y >= 0``
    of multipliers over the columns (``gens + [slack]``) when the verdict is
    true, a list ``z`` with ``z.g <= 0`` for every column and ``z.t > 0``
    when it is false, and ``None`` when the exact simplex method had to
    decide.

    ``method="simplex"`` skips the least squares method (and thus produces
    no certificate); it is much slower for more than about 7 variables.
    """
    if method == "auto":
        D, cols, t = homogenize(gens, nvars, v)
        A = [todense(c, D, as_float=True) for c in cols]       # columns
        b = todense(t, D, as_float=True)
        res = nnls(A, b)
        if res is not None:
            x, passive = res
            # residual r = b - A x
            Ax = [0.0] * (D + 1)
            for j, col in enumerate(A):
                xj = x[j]
                if xj == 0.0:
                    continue
                for i, cv in enumerate(col):
                    Ax[i] += cv * xj
            r = [bi - ai for bi, ai in zip(b, Ax)]
            rnorm = sum(ri * ri for ri in r) ** 0.5
            bnorm = sum(bi * bi for bi in b) ** 0.5
            if rnorm <= 1e-8 * max(1.0, bnorm):
                y = certify_true(cols, t, passive)
                if y is not None:
                    return True, y
            else:
                lines = [j for j, g in enumerate(gens) if g.line]
                z = certify_false(cols, lines, t, r, nvars, D)
                if z is None:
                    z = certify_false_exact(cols, t, passive, D)
                if z is not None:
                    return False, z
        SIMPLEX_FALLBACKS[0] += 1

    verdict = _implied_simplex(gens, nvars, v)
    return verdict, None


def implied(gens, nvars, v, method: str = "auto") -> bool:
    """Is  v.h + v[0] >= 0  implied by the generators? See decide()."""
    return decide(gens, nvars, v, method)[0]


def _implied_simplex(gens: list[Generator], nvars: int, v: dict[int, Fraction]) -> bool:
    m = (1 << nvars) - 1
    A = [[Fraction(0)] * len(gens) for _ in range(m)]
    for j, g in enumerate(gens):
        for k, x in g.a:
            A[k - 1][j] += x
    rhs = [Fraction(0)] * m
    for k, x in v.items():
        if k != 0:
            rhs[k - 1] = x
    cost = [g.b for g in gens]
    status, value = simplex(A, rhs, cost)
    if status == "infeasible":
        return False
    if status == "unbounded":
        return True
    return value <= v.get(0, Fraction(0))


_GRID = (1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 24, 32, 64, 128, 1024)


def simplify_certificate(gens, nvars, v, z, D):
    """Replace a Farkas certificate by an equivalent one with smaller
    numbers: round the entropies it implies to a small common denominator
    and verify the result exactly, then cancel the common factor. Returns
    ``z`` itself if no rounding verifies.
    """
    _, cols, t = homogenize(gens, nvars, v)

    def valid(c):
        return sdot(t, c) > 0 and all(sdot(col, c) <= 0 for col in cols)

    s = -z[D]
    if s > 0:
        h = [-zv / s for zv in z[1:D]]
        for d in _GRID:
            cand = [Fraction(-round(x * d)) for x in h]
            cand.append(Fraction(-d))
            # cand indices 0..D-1 correspond to subsets 1..D-1 plus constant D
            full = [Fraction(0)] + cand
            if valid(full):
                return _cancel_factor(full)
    else:
        peak = max((abs(zv) for zv in z[1:D]), default=Fraction(0))
        if peak == 0:
            return _cancel_factor(z)

        def f(k):
            return k * (2 * nvars + 1 - k)

        for m_ in _GRID:
            cand = [Fraction(0)]
            for S in range(1, D):
                x = z[S]
                cand.append(Fraction(-(round(-x * m_ / peak) + f(bin(S).count("1")))))
            cand.append(Fraction(0))
            if valid(cand):
                return _cancel_factor(cand)
    return _cancel_factor(z)


def _cancel_factor(c: list[Fraction]) -> list[Fraction]:
    """Scale a vector of rationals to coprime integers (a positive scaling,
    which changes neither the Farkas conditions nor the entropies it
    implies).
    """
    denom = reduce(lambda a, b: a * b // gcd(a, b), (x.denominator for x in c), 1)
    ints = [int(x * denom) for x in c]
    g = reduce(gcd, (abs(i) for i in ints), 0)
    if g == 0:
        return c
    return [Fraction(i // g) for i in ints]
